name: Example workflow for S3 Deploy
on: [ workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build
          
        - name: export
          run: npm run export

  
    
        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: .next
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ap-south-1
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: "/*"
            delete-removed: true
            no-cache: true
            private: true
            filesToInclude: ".*/*,*/*,**"
