
name: S3 Deployment
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build App
        run: npm run build
      - name: S3/CloudFront Deploy
        uses: staevs/s3-deploy-action@1.0.0
        if: success()
        with:
          args: --follow-symlinks --delete --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ap-south-1
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          S3_SOURCE_DIR: ".next"
