name: Example workflow for S3 Deploy
on: [ workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build
          
        #- name: export
         # run: npm run export

        - name: Deploy static site to S3 bucket
          run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET }}
          
        - name: update cloudfront 
          run : aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'"
    
