name: Update stage branch code with master branches

on:
  push:
    branches:
      - master

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
  contents: write

jobs:
  update-stage-branch-code:
    name: Merge master into stage branch after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       # with:
       #   token: ${{ github.token }}
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge master back to dev
        run: |
          git fetch origin master
          git checkout stage
          git pull 
          git merge master
          git push 
#           fetch-depth: 0 # Let's get all the branches
#       - name: Merge Master to Production branch
#         uses: devvspaces/merge-branches@v1
#         with:
#           token: ${{ github.token }}
#           from_branch: master
#           to_branch: stage
